### ISSUE TITLE
2017 Refactor

### ISSUE THREAD

**Issue by gokapaya** [gokapaya/cshelper#1]
*Tracking issue for the major refactor*

## todo:
- [x] manage state via CSV files (we get them from Google Forms/Sheets) anyway)
- [x] ~~integration with [WolfgangAxel/ClosetSantaMessagingBot](https://github.com/WolfgangAxel/ClosetSantaMessagingBot)~~
- [x] improve the matching algorithm
- [x] ~~keep user data out of the view of the operators (we only need usernames)~~
- [x] remove `boltclient/` code
- [x] improve CLI
- use the reddit bot more? possibly:
    - [ ] alerting
    - [x] ~~receive proofs from gifters~~
    - [ ] automating response to giftee
